version: '3'

services:
  angular-nginx-docker:
    image: 172.31.44.24:8083/angular-nginx-docker:latest
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4580:80
    deploy:
      replicas: 2
