version: '3'

services:
  angular-nginx-docker:
    image: 172.31.44.24:8083/angular-nginx-docker:latest_${JOBNAME}-${BUILDNUM}
    environment:
      NODE_ENV: production
    ports:
      - 4580:80
    networks:
      - overlay
    deploy:
      replicas: 2

 networks:
  overlay:
    external:
      name: epicnetwork
